<?php

return array (
  'Panda\\Foundation\\Http\\ClientRequestedAbstract' => '/Foundation/Http/ClientRequestedAbstract.php',
  'Panda\\Foundation\\Http\\ClientRequestedInterface' => '/Foundation/Http/ClientRequestedInterface.php',
  'Panda\\Foundation\\Http\\ClientResponseAbstract' => '/Foundation/Http/ClientResponseAbstract.php',
  'Panda\\Foundation\\Http\\ClientResponseInterface' => '/Foundation/Http/ClientResponseInterface.php',
  'Panda\\Foundation\\Http\\ControllerNativeAbstract' => '/Foundation/Http/ControllerNativeAbstract.php',
  'Panda\\Foundation\\Http\\ControllerNativeInterface' => '/Foundation/Http/ControllerNativeInterface.php',
  'Panda\\Foundation\\Http\\CookieContainerAbstract' => '/Foundation/Http/CookieContainerAbstract.php',
  'Panda\\Foundation\\Http\\CookieContainerInterface' => '/Foundation/Http/CookieContainerInterface.php',
  'Panda\\Foundation\\Http\\ProcessorEventAbstract' => '/Foundation/Http/ProcessorEventAbstract.php',
  'Panda\\Foundation\\Http\\ProcessorEventInterface' => '/Foundation/Http/ProcessorEventInterface.php',
  'Panda\\Foundation\\Http\\RoutingDispatchAbstract' => '/Foundation/Http/RoutingDispatchAbstract.php',
  'Panda\\Foundation\\Http\\RoutingDispatchInterface' => '/Foundation/Http/RoutingDispatchInterface.php',
  'Panda\\Foundation\\Support\\EssenceReadableAbstract' => '/Foundation/Support/EssenceReadableAbstract.php',
  'Panda\\Foundation\\Support\\EssenceReadableInstance' => '/Foundation/Support/EssenceReadableInstance.php',
  'Panda\\Foundation\\Support\\EssenceReadableInterface' => '/Foundation/Support/EssenceReadableInterface.php',
  'Panda\\Foundation\\Support\\EssenceWriteableAbstract' => '/Foundation/Support/EssenceWriteableAbstract.php',
  'Panda\\Foundation\\Support\\EssenceWriteableInstance' => '/Foundation/Support/EssenceWriteableInstance.php',
  'Panda\\Foundation\\Support\\EssenceWriteableInterface' => '/Foundation/Support/EssenceWriteableInterface.php',
  'Panda\\Foundation\\Support\\FlotationInstanceAbstract' => '/Foundation/Support/FlotationInstanceAbstract.php',
  'Panda\\Foundation\\Support\\FlotationInstanceInterface' => '/Foundation/Support/FlotationInstanceInterface.php',
  'Panda\\Foundation\\Support\\InstnacesProviderAbstract' => '/Foundation/Support/InstnacesProviderAbstract.php',
  'Panda\\Http\\ControllerAbstract' => '/Framework/Http/ControllerAbstract.php',
  'Panda\\Http\\ControllerInterface' => '/Framework/Http/ControllerInterface.php',
  'Panda\\Http\\ProcessorAbstract' => '/Framework/Http/ProcessorAbstract.php',
  'Panda\\Http\\ProcessorInterface' => '/Framework/Http/ProcessorInterface.php',
  'Panda\\Http\\Request' => '/Framework/Http/Request.php',
  'Panda\\Http\\RequestInterface' => '/Framework/Http/RequestInterface.php',
  'Panda\\Http\\Response' => '/Framework/Http/Response.php',
  'Panda\\Http\\ResponseInterface' => '/Framework/Http/ResponseInterface.php',
  'Panda\\Http\\Router' => '/Framework/Http/Router.php',
  'Panda\\Provider' => '/Framework/Provider.php',
);
