<?php

return array (
  'Panda\\Foundation\\Http\\ClientRequestedAbstract' => '/Foundation/Http/ClientRequestedAbstract.php',
  'Panda\\Foundation\\Http\\ClientRequestedInterface' => '/Foundation/Http/ClientRequestedInterface.php',
  'Panda\\Foundation\\Http\\ClientResponseAbstract' => '/Foundation/Http/ClientResponseAbstract.php',
  'Panda\\Foundation\\Http\\ClientResponseInterface' => '/Foundation/Http/ClientResponseInterface.php',
  'Panda\\Foundation\\Http\\ControllerListener' => '/Foundation/Http/ControllerListener.php',
  'Panda\\Foundation\\Http\\CookieContainerAbstract' => '/Foundation/Http/CookieContainerAbstract.php',
  'Panda\\Foundation\\Http\\CookieContainerInterface' => '/Foundation/Http/CookieContainerInterface.php',
  'Panda\\Foundation\\Http\\EssenceImplementation\\EssenceCookie' => '/Foundation/Http/EssenceImplementation/EssenceCookie.php',
  'Panda\\Foundation\\Http\\EssenceImplementation\\EssenceFiles' => '/Foundation/Http/EssenceImplementation/EssenceFiles.php',
  'Panda\\Foundation\\Http\\EssenceImplementation\\EssenceHeaders' => '/Foundation/Http/EssenceImplementation/EssenceHeaders.php',
  'Panda\\Foundation\\Http\\EssenceImplementation\\EssenceServer' => '/Foundation/Http/EssenceImplementation/EssenceServer.php',
  'Panda\\Foundation\\Http\\RouterImplementation\\EssenceRoutes' => '/Foundation/Http/RouterImplementation/EssenceRoutes.php',
  'Panda\\Foundation\\Http\\RoutingDispatchAbstract' => '/Foundation/Http/RoutingDispatchAbstract.php',
  'Panda\\Foundation\\Support\\EssenceReadableAbstract' => '/Foundation/Support/EssenceReadableAbstract.php',
  'Panda\\Foundation\\Support\\EssenceReadableInstance' => '/Foundation/Support/EssenceReadableInstance.php',
  'Panda\\Foundation\\Support\\EssenceReadableInterface' => '/Foundation/Support/EssenceReadableInterface.php',
  'Panda\\Foundation\\Support\\EssenceWriteableAbstract' => '/Foundation/Support/EssenceWriteableAbstract.php',
  'Panda\\Foundation\\Support\\EssenceWriteableInstance' => '/Foundation/Support/EssenceWriteableInstance.php',
  'Panda\\Foundation\\Support\\EssenceWriteableInterface' => '/Foundation/Support/EssenceWriteableInterface.php',
  'Panda\\Http\\Controller' => '/Framework/Http/Controller.php',
  'Panda\\Http\\Request' => '/Framework/Http/Request.php',
  'Panda\\Http\\RequestInterface' => '/Framework/Http/RequestInterface.php',
  'Panda\\Http\\Response' => '/Framework/Http/Response.php',
  'Panda\\Http\\ResponseInterface' => '/Framework/Http/ResponseInterface.php',
  'Panda\\Http\\Router' => '/Framework/Http/Router.php',
);
